<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SaelBrowser</AssemblyName>
    <RootNamespace>SaelBrowser.Windows</RootNamespace>
    <Version>0.1.0</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SaelBrowser.Core/SaelBrowser.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <Content Include="Resources/Sael/sael.js" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
